<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.11.0 on darwin)" generated="20221222 21:31:30.211" rpa="false">
<suite id="s1" name="sampleTest" source="/Users/adarsh/Documents/CE/robot-selenium-example/sampleTest.robot">
<test id="s1-t1" name="BrowserStack Demo Website">
<errors>
<msg timestamp="20221222 21:31:30.241" level="ERROR">Unexpected error: TypeError: TestStatus.__init__() got an unexpected keyword argument 'skip_on_failure'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/run.py", line 443, in main
    result = suite.run(settings)
             ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/running/model.py", line 259, in run
    self.visit(runner)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/model/testsuite.py", line 174, in visit
    visitor.visit_suite(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/model/visitor.py", line 88, in visit_suite
    suite.tests.visit(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/model/testcase.py", line 78, in visit
    visitor.visit_test(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robot/running/runner.py", line 122, in visit_test
    status = TestStatus(self._suite_status, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/browserstack_sdk/__init__.py", line 1240, in bstack11ll11l_opy_
    bstack1ll1ll1_opy_(self, parent, test, skip_on_failure=skip_on_failure, rpa=rpa)</msg>
</errors>
</robot>
